# Generated by Django 5.1.2 on 2024-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
